spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ningfoj-backend-user-service
          uri: lb://ningfoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: ningfoj-backend-question-service
          uri: lb://ningfoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: ningfoj-backend-judge-service
          uri: lb://ningfoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: ningfoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    #第一个配置，开启gateway聚合组件
    enabled: true
    #设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      #开启discover模式
      enabled: true
      version: swagger2